config/routes.rb
Jensenlocksmithing::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get "log_out" => "sessions#destroy", as: "log_out"
    get "login" => "sessions#new", as: "login"

    get "home" => "page#home"
    get "services" => "page#services"
    get "frequently_asked_questions" => "page#faq"
    get "discounts_coupons" => "page#discounts" 
    get "contact_us" => "page#contact_us"

    resources :reviews, only: [:new, :create]
    resources :blogs, only: [:index, :show]

    namespace :admin do
      root to: 'page#panel'
      get "panel" => "page#panel"
      match "/savesort" => 'admin/categories#savesort'

      resources :page_headers
      resources :monthly_posts
      resources :coupons
      resources :logos
      resources :faqs 
      resources :blogs
      
      resources :categories, except: [:index, :show] do
        collection do
          post :sort 
          get :new_subcategory
          get :edit_subcategory
        end
      end

      resources :reviews, except: [:new, :show, :destroy, :create]
      resources :contacts, except: [:new, :show, :destroy, :create]
      resources :users

      resources :products do
        member do
          put :move_up
          put :move_down
        end 
      end
    end
    #End Admin Namespace

    

    # Is this needed?
    resources :children, :controller => :categories, :only => [:index, :new, :create, :new_subcategory]
   
  resources :sessions

  root to: 'page#home' # handles /en/
    
  match "*path", to: "page#not_found" # handles /en/fake/path/whatever
  end 

  root to: redirect("/#{I18n.default_locale}") # handles /
  match 'request_bid' => 'request_bid#new', :as => 'request_bid', :via => :get
  match 'request_bid' => 'request_bid#create', :as => 'request_bid', :via => :post
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}")

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	# Add Blog Category
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  acts_as_list :scope => :parent_id
  attr_accessible :name, :parent_id, :position, :image
  has_many :products

  mount_uploader :image, CategoryUploader

	scope :position, order("position asc")
	scope :categories, where("depth IS NULL")
	scope :subcategories, where("parent_id IS NOT NULL")
	scope :with_depth_below, lambda { |level|
  	  where(self.arel_table[:depth].lt(level))
    }
  scope :services, where("name = 'Services'")
  scope :products, where("name = 'Products'")
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	attr_accessible :phone, :email, :facebook, :twitter, :google_reviews
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
	attr_accessible :name, :description, :expiration
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  acts_as_list
  attr_accessible :question, :answer, :position
  translates :question, :answer
end

app/models/logo.rb
class Logo < ActiveRecord::Base
	mount_uploader :image, LogoUploader
	scope :default, where(default: true)
	scope :latest, order('created_at ASC')
	attr_accessible :name, :image, :default

	def falsify_all_others
      Logo.where('id != ?', self.id).each do |item|
    	item.default = false
    	item.save
    end
end
	
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  # validates :name, :email, :subject, :body, :presence => true
  validates :email, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/monthly_post.rb
class MonthlyPost < ActiveRecord::Base
	translates :body
	attr_accessible :body
	scope :newest_first, :order => 'created_at DESC'
end

app/models/page_header.rb
class PageHeader < ActiveRecord::Base
	translates :title, :description
	scope :home, where("page = 1")
	scope :services, where("page = 2")
	scope :faqs, where("page = 3")
	scope :discounts, where("page = 4")
	scope :contact_us, where("page = 5")
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  acts_as_list :scope => :category
  scope :position, order("position asc")
  attr_accessible :name, :position, :price, :description, :category_id, :image
  mount_uploader :image, ProductUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
	attr_accessible :first_name, :last_name, :body, :active
	translates :body
	scope :last_three, limit(3)
	scope :active, where(active: true)
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < PageController
  # before_filter :authorize
  before_filter :add_breadcrumbs
  def new
    @product = Product.new
    add_breadcrumb "New Product", new_admin_product_path
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to admin_products_path, :notice => "Product Created! Woo Hoo!"
    else
      render "new"
    end
  end

  def edit
    add_breadcrumb "Edit Product", edit_admin_product_path
    @product = Product.find(params[:id]) 
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product has been obliterated!"
    redirect_to admin_products_path
  end

  def update
    @product = Product.find(params[:id])

    @product.insert_at(params[:position].to_i)

    if @product.update_attributes(params[:product])
      
      flash[:notice] = "Changed that for you!"
      redirect_to admin_products_path
    else 
      flash[:alert] = "Product has not been updated."
      render :action => "edit"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def index
    @categories = params[:id] ? Category.find(params[:id]).children : Category.categories
    @products = Product.all
    @count = Category.count
  end 

  def move_up
    @product = Product.find(params[:id])
    @product.move_higher
    redirect_to admin_products_path
  end

  def move_down
    @product = Product.find(params[:id])
    @product.move_lower
    redirect_to admin_products_path
  end

  def add_breadcrumbs
    add_breadcrumb "Admin", admin_panel_path
    add_breadcrumb "Manage Categories & Products", admin_products_path
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_form.html.erb
<div id="product_notes">
<table>
  <th> <h4> Product Notes </h4> </th>
  <tr>
    <td>
      Name shouldn't be blank, and price can be empty. If no price is listed it will ignore it and not display one. Select the category you want this subcategory to go under.
    </td>
  </tr>
</table>
</div>
<br />
<table>
<%= form_for [:admin, @product] do |f| %>
  <tr>
    <td><%= f.label(:name) %></td>
      <td><%= f.text_field :name %></td> 
  </tr>
  <tr>
    <td><%= f.label(:price) %></td>
    <td><%= f.text_field :price %></td>
  </tr>
  <tr>
    <td><%= f.label(:description) %></td>
    <td><%= f.text_area :description %></td>
  </tr>
  <tr>
    <td><%= f.label(:category_id) %></td>
    <td><%= f.select(:category_id, options_from_collection_for_select(Category.subcategories, :id, :name)) %></td>
  </tr>

  <!-- TODO: Add Ability to upload images if needed -->
  <%# f.file_field :image %>
<tr>
  <td></td>
  <td><%= f.submit("Submit") %></td>
</tr>
<% end %>
</table>

app/views/admin/products/edit.html.erb
<%= render("form") %>

app/views/admin/products/index.html.erb
<div id="instructions">
<table>
  <th> <h4> Icons </h4> </th>
  <th> <h4> Instructions </h4> </th>
  <tr>
    <td>
      The <%= image_tag("edit_16.png") %> Icon means Edit 
      
      <br />The <%= image_tag("delete_16.png") %> Icon means Delete
    </td>
    <td>
      Reorder Categories and Subcategories - simply left click and drag the name to the spot you want, and click "Save Order".
      To Reorder Products simply click the up or down arrows, and it will automatically refresh and save the order. No need to click "Save Order". To Edit or Delete them, click their edit/delete icons
    </td>
  </tr>
  <tr>

  </tr>
</table>
</div>
<br />

<nav id="admin">
<ul>
  <li><%= link_to "New Category", new_admin_category_path %></li>
  <li><%= link_to "New Subcategory", new_subcategory_admin_categories_path %></li>
  <li><%= link_to "New product", new_admin_product_path %></li>
</ul>
</nav>

<h3>Categories - <a href='#' id='serialize'>Save Order</a> | <a href="javascript:location.reload(true)">Reset Order</a></h3>
<div id="category">
  <ul id="sortable">
    <% Category.roots.each do |cat| %>
      <li id='category_<%= cat.id %>'>
        <span><%= cat.name %></span>
     
        <%= link_to image_tag("edit_16.png",:alt => "Edit Category"), edit_admin_category_path(cat) %>
        <%= link_to image_tag("delete_16.png"), admin_category_path(cat), :method => :delete, :confirm => "Are you sure you want to delete this category?" %>
        <%= render 'admin/shared/admin_subcategories', :item => cat unless cat.leaf? %>
    </li>
       <hr>
  <% end %>
  <!-- end category -->
  
</ul>
  </div>

app/views/admin/products/new.html.erb
<%= render("form") %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
<p>
  <%= f.label(:name) %>
  <%= f.text_field :name %>
</p>
<p>
  <%# f.label(:position) %>
  <%# f.text_field :position %>
</p>
<p>
  <%= f.label(:price) %>
  <%= f.text_field :price %>
</p>
<p>
  <%= f.label(:description) %>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.label(:category_id) %>
  <%= f.select(:category_id, options_from_collection_for_select(Category.subcategories, :id, :name)) %>
</p>

<p>
  Image: <%= f.file_field :image %>
</p>
<p>
  <%= f.submit("Submit") %>
</p>
<% end %>

app/views/products/edit.html.erb
<%= render("form") %>

app/views/products/index.html.erb
<nav id="admin">
<ul>
  <li><%= link_to "New Category", new_category_path %></li>
  <li><%= link_to "New Subcategory", new_subcategory_categories_path %></li>
  <li><%= link_to "New product", new_product_path %></li>
</ul>
</nav>

<h3>Categories</h3>
<div id="category">
<ul id="sortable">
  <% for cat in Category.roots %>
    <li id='category_<%= cat.id %>'>
    <span><%= cat.name %></span>
    <span>Depth: <%= cat.depth %>
     
      <%= link_to raw('<span class="button-edit">Edit</span>'), edit_category_path(cat) %>
      <%= link_to raw('<span class="button-delete">Delete</span>'), cat, :method => :delete, :confirm => "Are you sure you want to delete this category?" %><br /> <br />
      <%= render 'shared/children', :item => cat unless cat.leaf? %>
    </li>
       <hr>
  <% end %>
  <!-- end category -->
  <h3><a href='#' id='serialize'>Save Order</a> | <a href="javascript:location.reload(true)">Reset</a></h3>
</ul>
  </div>

app/views/products/new.html.erb
<%= render("form") %>